function(embed_assets TARGET ASSET_DIR)
    # Generated files
    set(GENERATED_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated")
    set(GENERATED_INCLUDE_DIR "${GENERATED_DIR}/include")
    set(GENERATED_EMBEDDED_DIR "${GENERATED_INCLUDE_DIR}/embedded")

    file(MAKE_DIRECTORY "${GENERATED_EMBEDDED_DIR}")

    # Find all assets
    file(GLOB_RECURSE ASSET_FILES CONFIGURE_DEPENDS "${ASSET_DIR}/*")

    set(GENERATED_SOURCES "")
    set(GENERATED_HEADERS "")

    # Used to generate the master assets.h
    set(ASSET_INCLUDES "")
    set(ASSET_ENTRIES "")

    # Generate one header + source for every asset

    foreach(ASSET ${ASSET_FILES})

        if(IS_DIRECTORY "${ASSET}")
            continue()
        endif()

        # Relative path inside assets/
        file(RELATIVE_PATH RELATIVE_ASSET
            "${ASSET_DIR}"
            "${ASSET}"
        )

        file(TO_CMAKE_PATH
            "${RELATIVE_ASSET}"
            RELATIVE_ASSET
        )

        # Convert filename to valid C identifier
        string(REGEX REPLACE
            "[^a-zA-Z0-9_]"
            "_"
            ASSET_ID
            "${RELATIVE_ASSET}"
        )

        # Prevent identifiers beginning with a number
        string(SUBSTRING "${ASSET_ID}" 0 1 FIRST_CHAR)

        if(FIRST_CHAR MATCHES "[0-9]")
            set(ASSET_ID "_${ASSET_ID}")
        endif()

        # Header/source names
        set(HEADER_FILE "${GENERATED_EMBEDDED_DIR}/${ASSET_ID}.h")
        set(SOURCE_FILE "${GENERATED_DIR}/${ASSET_ID}.c")

        # Read binary data
        file(READ "${ASSET}" HEX_DATA HEX)

        string(LENGTH "${HEX_DATA}" HEX_LENGTH)

        math(EXPR BYTE_COUNT
            "${HEX_LENGTH} / 2"
        )

        # Header
        string(TOUPPER
            "${ASSET_ID}"
            HEADER_GUARD_ID
        )

        file(WRITE "${HEADER_FILE}"
"#ifndef EMBEDDED_${HEADER_GUARD_ID}_H
#define EMBEDDED_${HEADER_GUARD_ID}_H

#include <stddef.h>

#ifdef __cplusplus
extern \"C\" {
#endif

extern const unsigned char embedded_${ASSET_ID}[];
extern const size_t embedded_${ASSET_ID}_size;

#ifdef __cplusplus
}
#endif

#endif
"
        )

        # Source
        file(WRITE "${SOURCE_FILE}"
"#include <stddef.h>
#include <stdint.h>

const unsigned char embedded_${ASSET_ID}[] = {
"
        )

        if(BYTE_COUNT GREATER 0)
            math(EXPR LAST_BYTE "${BYTE_COUNT} - 1")

            foreach(INDEX RANGE 0 ${LAST_BYTE})

                math(EXPR OFFSET "${INDEX} * 2")
                string(SUBSTRING "${HEX_DATA}" ${OFFSET} 2 BYTE)
                file(APPEND "${SOURCE_FILE}" "0x${BYTE},")
                math(EXPR COLUMN "${INDEX} % 12")

                if(COLUMN EQUAL 11)
                    file(APPEND "${SOURCE_FILE}" "\n")
                endif()

            endforeach()

        endif()

        file(APPEND "${SOURCE_FILE}"
"
};

const size_t embedded_${ASSET_ID}_size = ${BYTE_COUNT};
"
        )

        # Track generated files
        list(APPEND GENERATED_SOURCES "${SOURCE_FILE}")
        list(APPEND GENERATED_HEADERS "${HEADER_FILE}")

        # Entry for master assets.h
        string(APPEND ASSET_INCLUDES
            "#include <embedded/${ASSET_ID}.h>\n"
        )

        string(APPEND ASSET_ENTRIES
            "/* ${RELATIVE_ASSET} */\n"
            "#define EMBEDDED_${ASSET_ID} embedded_${ASSET_ID}\n"
            "#define EMBEDDED_${ASSET_ID}_SIZE embedded_${ASSET_ID}_size\n\n"
        )

    endforeach()

    # Generate master assets.h
    set(MASTER_HEADER "${GENERATED_EMBEDDED_DIR}/assets.h")
    file(WRITE "${MASTER_HEADER}"
"#ifndef EMBEDDED_ASSETS_H
#define EMBEDDED_ASSETS_H

/*
 * Automatically generated by CMake.
 *
 * Do not edit this file manually.
 */

${ASSET_INCLUDES}

/*
 * Convenient aliases for the embedded resources.
 */

${ASSET_ENTRIES}

#endif
"
    )

    list(APPEND GENERATED_HEADERS "${MASTER_HEADER}")

    # Add generated C files to target
    target_sources(${TARGET} PRIVATE
        ${GENERATED_SOURCES}
    )

    # Make generated headers available as: #include <embedded/assets.h>
    target_include_directories(${TARGET} PRIVATE
        "${GENERATED_INCLUDE_DIR}"
    )

    # Make CMake aware of generated headers
    set_source_files_properties(
        ${GENERATED_HEADERS}
        PROPERTIES
        GENERATED TRUE
    )

endfunction()
